spring.application.name=Auth 


spring.datasource.url=jdbc:postgresql://localhost:5432/Auth
spring.datasource.username=postgres
spring.datasource.password=0000

# Hibernate properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# Ensure the cookie isn't restricted to just the backend port
server.servlet.session.cookie.path=/

logging.level.org.springframework.security=DEBUG

server.servlet.session.cookie.same-site=none
server.servlet.session.cookie.secure=false
server.servlet.session.cookie.http-only=true
